version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      - monitoring
    ports:
      - '8087:8086'
    volumes:
      - ./influxdb:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - monitoring
    ports:
      - '3001:3000'

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - monitoring
    ports:
      - '3002:3000'
    environment:
      - REACT_APP_GRAPHQL_URL=http://localhost:4000/graphql
    depends_on:
      - influxdb
      - grafana

networks:
  monitoring:
